#!/bin/bash

myhostname=$(hostname)
mydate=$(date)
uptime=$(uptime -p)
os=$(source /etc/os-release && echo "$NAME, Version: $VERSION")
cpu=$(lscpu | grep "Model name")
ram=$(free -h | grep "Mem" | awk '{print $2}')
disks=$(lsblk -d -o MODEL,SIZE)
video=$(lshw -class video | grep -E "vendor|product")
host=$(ip r s default | awk '{print $9}')
gateway=$(ip r s default | awk '{print $3}')
dns=$(cat /etc/resolv.conf | grep "nameserver")

users=$(users)
#diskspace=$(df -h)
ufw=$(sudo ufw status | awk '{print $2}')

cat <<EOF

System Report for $myhostname generated by $USER, on $mydate
 
System Information
------------------
OS: $os
Uptime: $uptime
CPU: $cpu
RAM: $ram
Disk(s): $disks
Video: $video
Host Address: $host
Gateway IP: $gateway
DNS Server: $dns
 
System Status
-------------
Users Logged In: $users
Disk Space: FREE SPACE FOR LOCAL FILESYSTEMS IN FORMAT: /MOUNTPOINT N
Process Count: N
Load Averages: N, N, N
Listening Network Ports: N, N, N, ...
UFW Status: $ufw

EOF
